### ISSUE TITLE
I can not install the app

### ISSUE THREAD

**Issue by hench-ye** [LedgerHQ/app-boilerplate#7]
When I run 'make load', I can not install the app. Is there something wrong? thank you.

`TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=2.0.0
BOLOS_ENV=/home/hench/BOLOS/dev-env/CC/others
BOLOS_ENV=/home/hench/BOLOS/dev-env/CC/others
python3 -m ledgerblue.loadApp --curve secp256k1 --appFlags 0x240 --path "44'" --tlv --targetId 0x31100004 --targetVersion="2.0.0" --delete --fileName bin/app.hex --appName "Boilerplate" --appVersion "1.0.1" --dataSize $((0x`cat debug/app.map |grep _envram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'` - 0x`cat debug/app.map |grep _nvram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'`)) `ICONHEX=\`python3 /home/hench/BOLOS/dev-env/SDK/nanos-secure-sdk/icon3.py --hexbitmaponly icons/nanos_app_boilerplate.gif  2>/dev/null\` ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"` 
Generated random root public key : b'04dc154c7b09325db148499fbb8219ba542f6c042668d287812977a62c833b656bdf69cbd5a44f8c7e3d395dee9864034e4e36755de956d4067ae8487483857462'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hench/BOLOS/dev-env/ledger_py3/lib/python3.8/site-packages/ledgerblue/loadApp.py", line 199, in <module>
    dongle = getDongle(args.apdu)
  File "/home/hench/BOLOS/dev-env/ledger_py3/lib/python3.8/site-packages/ledgerblue/comm.py", line 216, in getDongle
    dev.open_path(hidDevicePath)
  File "hid.pyx", line 74, in hid.device.open_path
OSError: open failed
make: *** [Makefile:111: load] Error 1`

**Comment by ixje** [comment]
sounds like a permission problem. Did you add the udev rules?
```
wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
```
if you did, try adding `OWNER` to the rule of the device you have e.g.
```
# Nano S
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0001|1000|1001|1002|1003|1004|1005|1006|1007|1008|1009|100a|100b|100c|100d|100e|100f|1010|1011|1012|1013|1014|1015|1016|1017|1018|1019|101a|101b|101c|101d|101e|101f", TAG+="uaccess", TAG+="udev-acl OWNER="your_user_name"
```

**Comment by lpascal-ledger** [comment]
Closing as 6months+ old
