### ISSUE TITLE
bad "Getting Started" link in README?

### ISSUE THREAD

**Issue by simonhf** [LedgerHQ/app-boilerplate#8]
The `README.md` file has a bad link called "Getting Started" which points to [1] which does not exist. Where should it point? To [2]?

[1] https://ledger.readthedocs.io/en/latest/userspace/introduction.html
[2] https://developers.ledger.com/docs/nano-app/introduction/

**Comment by pscott** [comment]
[2] indeed :)

**Comment by pscott** [comment]
Fixed by https://github.com/LedgerHQ/app-boilerplate/commit/8877753dc38fc3264978599e24f7838ad59732ff, thanks for notifying us :)
